### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by petertimwalker** [petertimwalker/friends#1]
```
2022-07-26T03:34:51.928274+00:00 heroku[web.1]: State changed from crashed to starting
2022-07-26T03:34:55.485831+00:00 heroku[web.1]: Starting process with command `npm start`
2022-07-26T03:34:56.909169+00:00 app[web.1]: 
2022-07-26T03:34:56.909180+00:00 app[web.1]: > friends@0.1.0 start /app
2022-07-26T03:34:56.909181+00:00 app[web.1]: > rails s
2022-07-26T03:34:56.909181+00:00 app[web.1]: 
2022-07-26T03:34:57.055107+00:00 app[web.1]: Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.3.11). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.11`.
2022-07-26T03:34:57.091956+00:00 app[web.1]: /usr/lib/ruby/2.7.0/bundler/definition.rb:495:in `validate_ruby!': Your Ruby version is 2.7.0, but your Gemfile specified 2.6.10 (Bundler::RubyVersionMismatch)
2022-07-26T03:34:57.091989+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/bundler/definition.rb:470:in `validate_runtime!'
2022-07-26T03:34:57.091989+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/bundler.rb:143:in `setup'
2022-07-26T03:34:57.091990+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
2022-07-26T03:34:57.091990+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
2022-07-26T03:34:57.091990+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
2022-07-26T03:34:57.091990+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
2022-07-26T03:34:57.091992+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
2022-07-26T03:34:57.091993+00:00 app[web.1]: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
2022-07-26T03:34:57.091994+00:00 app[web.1]: from /app/config/boot.rb:3:in `<top (required)>'
2022-07-26T03:34:57.091997+00:00 app[web.1]: from /app/bin/rails:8:in `require_relative'
2022-07-26T03:34:57.092005+00:00 app[web.1]: from /app/bin/rails:8:in `<main>'
2022-07-26T03:34:57.097819+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2022-07-26T03:34:57.097949+00:00 app[web.1]: npm ERR! errno 1
2022-07-26T03:34:57.099570+00:00 app[web.1]: npm ERR! friends@0.1.0 start: `rails s`
2022-07-26T03:34:57.099570+00:00 app[web.1]: npm ERR! Exit status 1
2022-07-26T03:34:57.099583+00:00 app[web.1]: npm ERR!
2022-07-26T03:34:57.099644+00:00 app[web.1]: npm ERR! Failed at the friends@0.1.0 start script.
2022-07-26T03:34:57.099702+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-07-26T03:34:57.102524+00:00 app[web.1]: 
2022-07-26T03:34:57.102622+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2022-07-26T03:34:57.102658+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2022-07-26T03_34_57_100Z-debug.log
2022-07-26T03:34:57.244507+00:00 heroku[web.1]: Process exited with status 1
2022-07-26T03:34:57.327307+00:00 heroku[web.1]: State changed from starting to crashed
2022-07-26T03:38:01.005311+00:00 app[api]: Starting process with command `rake db:migrate` by user petertwalker@gmail.com
2022-07-26T03:38:04.820189+00:00 heroku[run.6054]: Awaiting client
2022-07-26T03:38:04.835560+00:00 heroku[run.6054]: Starting process with command `rake db:migrate`
2022-07-26T03:38:04.899313+00:00 heroku[run.6054]: State changed from starting to up
2022-07-26T03:38:08.470396+00:00 heroku[run.6054]: Process exited with status 18
2022-07-26T03:38:08.526701+00:00 heroku[run.6054]: State changed from up to complete
2022-07-26T03:41:27.425957+00:00 app[api]: Starting process with command `rake db:migrate` by user petertwalker@gmail.com
2022-07-26T03:41:31.648174+00:00 heroku[run.1636]: State changed from starting to up
2022-07-26T03:41:31.774604+00:00 heroku[run.1636]: Awaiting client
2022-07-26T03:41:31.794557+00:00 heroku[run.1636]: Starting process with command `rake db:migrate`
2022-07-26T03:41:35.451401+00:00 heroku[run.1636]: Process exited with status 18
2022-07-26T03:41:35.497725+00:00 heroku[run.1636]: State changed from up to complete
2022-07-26T03:42:33.964425+00:00 app[api]: Starting process with command `rake db:migrate` by user petertwalker@gmail.com
2022-07-26T03:42:38.021439+00:00 heroku[run.9695]: Awaiting client
2022-07-26T03:42:38.022716+00:00 heroku[run.9695]: State changed from starting to up
2022-07-26T03:42:38.038691+00:00 heroku[run.9695]: Starting process with command `rake db:migrate`
2022-07-26T03:42:41.894963+00:00 heroku[run.9695]: Process exited with status 18
2022-07-26T03:42:41.938402+00:00 heroku[run.9695]: State changed from up to complete
2022-07-26T03:47:29.287625+00:00 app[api]: Starting process with command `rake db:migrate` by user petertwalker@gmail.com
2022-07-26T03:47:33.534559+00:00 heroku[run.8569]: State changed from starting to up
2022-07-26T03:47:34.033726+00:00 heroku[run.8569]: Awaiting client
2022-07-26T03:47:34.053929+00:00 heroku[run.8569]: Starting process with command `rake db:migrate`
2022-07-26T03:47:38.052574+00:00 heroku[run.8569]: Process exited with status 18
2022-07-26T03:47:38.107376+00:00 heroku[run.8569]: State changed from up to complete
2022-07-26T03:50:25.735982+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ptw-friends.herokuapp.com request_id=c77a2b43-34ea-479b-95d3-cf8484251969 fwd="71.233.245.150" dyno= connect= service= status=503 bytes= protocol=https
2022-07-26T03:50:25.799957+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ptw-friends.herokuapp.com request_id=b9a8c44a-6ee6-40f2-bf73-16d52a8dc349 fwd="71.233.245.150" dyno= connect= service= status=503 bytes= protocol=https

```

**Comment by petertimwalker** [comment]
HAd to upgrade to Ruby 2.7
